language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "danielchesters-github"
    token:
      secure: "enjHVOyI1SwwC94N2kG3jwQoxxis2iv04MKy1MrFhT/dT1MRZjcVuWPmwYRQCjKPURbh5XZn+wKayb++HxrCnoL57YS+9qNb263wDXXRNc5imvRCubY29IEgWJnyVbCLAerbeoGeJda0BizHgjnVz31eqPyhLL/B9NiHY++5HJk="
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
