language: java
before_install:
  jdk_switcher use oraclejdk9
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default
env:
  - JAVA_OPTS='--permit-illegal-access'
