language: java
before_script:
  - if [[ "x$JDK" == *'x9'* ]]; then remove_dir_from_path $JAVA_HOME/bin; export JAVA_HOME=/usr/lib/jvm/java-9-oracle; export PATH=$JAVA_HOME/bin:$PATH; java -Xmx32m -version; fi

jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java9-installer
env:
  - JDK=9 JAVA_OPTS='--permit-illegal-access'
