language: java
sudo: required
dist: trusty
group: edge
jdk: oraclejdk9
env: JAVA_OPTS='--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED'
